escreva = input('escreva algo: ')
print('o tipo primitivo desse valoe é: ', type(escreva))
print('só tem espaços?', escreva.isspace())
print('é um número?', escreva.isnumeric())
print('é alfabético?', escreva.isalpha())
print('é alfanumérico?', escreva.isalnum())
print('está em maiúsculo?', escreva.isupper())
print('está em minúsculo?', escreva.islower())
print('está capitalizada?', escreva.istitle())

'''utilizando o format'''
e = input('escreva algo: ')
print('só tem espaços? {}'.format(e.isspace()))
print('é um número? {}'.format(e.isnumeric()))
print('é alfabético {}'.format(e.isalpha()))
print('é alfanumérico {}'.format(e.isalnum()))
print('está em maiúsculo? {}'.format(e.isupper()))
print('está em minúsculo? {}'.format(e.islower()))
print('está capitalizada? {}'.format(e.istitle()))